Django/blog/blog/urls.py
from django.contrib import admin
from django.urls import path
from about.views import get_about_data
from article.views import article_create
from main.views import index
from django.conf.urls.static import static
from blog import settings
from article.views import article_show
from comment.views import create_comment



urlpatterns = [
    path('about/', get_about_data, name='about_data'),
    path('article/create', article_create, name='article_create'),
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('<int:page>', index, name='index'),
    path('article_show/<int:id>/', article_show, name='article_show'),
    path('article/<int:article_id>/comment/create', create_comment, name='create_comment')
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/blog/about/models.py
from django.db import models

class About(models.Model):
    email = models.EmailField()
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    message = models.CharField(max_length=200)
    allow_mailing = models.BooleanField(default=False)

Django/blog/article/models.py
from django.db import models
from django.db.models.fields import CharField
from datetime import datetime

def image_save_path(instance, filename):
    return 'article/{0}/{1}'.format(datetime.today().strftime('%Y-%m-%d'), filename)

class Article(models.Model):
    title = models.CharField(max_length=100)
    shot_description = models.CharField(max_length=300, null=True)
    description = models.CharField(max_length=2000)
    image = models.ImageField(upload_to=image_save_path, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ('-created_date',)

Django/blog/comment/models.py
from django.db import models
from article.models import Article

class Comment(models.Model):
    name = models.CharField(max_length=100)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    class Meta:
        ordering = ('-created_date',)

Django/blog/main/models.py
from django.db import models

# Create your models here.

Django/blog/about/forms.py
from django import forms
from about.models import About

class AboutForm(forms.ModelForm):
    class Meta:
        model = About
        fields = '__all__'

Django/blog/comment/forms.py
from django import forms
from django.forms import fields
from comment.models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'text') 

Django/blog/about/views.py
from django.shortcuts import render
from about.forms import AboutForm
from about.models import About


def get_about_data(request):
    if request.method == 'POST':
        data_form = AboutForm(data=request.POST)
        if data_form.is_valid():
            email = data_form.cleaned_data['email']
            first_name = data_form.cleaned_data['first_name']
            last_name = data_form.cleaned_data['last_name']
            message = data_form.cleaned_data['message']
            allow_mailing = data_form.cleaned_data['allow_mailing']
            about_object = About(email = email, first_name = first_name, last_name = last_name, message = message, allow_mailing = allow_mailing)
            about_object.save()
            print('Saved')
    form = AboutForm()
    about_data = About.objects.all()
    return render(request, 'about.html', {'form':form, 'data':about_data})

Django/blog/article/views.py
from django.shortcuts import render
from article.form import ArticleCreateForm
from article.models import Article
from comment.forms import CommentForm
from comment.models import Comment

def article_create(request):
    if request.method == 'POST':
        print('Create')
        article_form = ArticleCreateForm(request.POST, request.FILES)
        if article_form.is_valid():
            article_form.save()
            print('Saved')
        else:
            print('Errors')
            return render(request, 'article_create.html', {'form': article_form, 'error': article_form.errors})   
    form = ArticleCreateForm()
    return render(request, 'article_create.html', {'form' : form})

def article_show(request, id):
    article_object = Article.objects.get(id=id)
    form = CommentForm()
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        print(comment_form)
        if comment_form.is_valid():
            cd = comment_form.cleaned_data
            comment_object = Comment(name=cd['name'], text=cd['text'], article=article_object)
            comment_object.save()
            print('saved')
        else:
            print('error')
    comment_object = Comment.objects.filter(article = article_object)
    comments_count = comment_object.count()
    print(comments_count)
    # print(comment_object)
    return render(request, 'article_show.html', {'article': article_object, 'form': form, 'comments': comment_object, 'count':
    comments_count}) 

            

Django/blog/comment/views.py
from django.shortcuts import render
from comment.forms import CommentForm
from comment.models import Comment

def create_comment(request, article_id):
    if request.method == 'POST':
        print('+')
        comment_form = CommentForm(request.POST)
        print('-')
        if comment_form.is_valid():
            comment_object = Comment()
            comment_object.save()
            print('saved')
    comment = Comment.objects.all()
    comments = Comment.objects.filter(article__id=article_id)
    return render(request, 'article_show.html')

Django/blog/main/views.py
import math
from django.shortcuts import render
from article.models import Article
from math import ceil

def index(request, page=1):
    articles_in_page = 2
    offset = articles_in_page * (page - 1)
    articles = Article.objects.all() 
    article_count = articles.count()
    pages_range = range(1, int(math.ceil(article_count/ articles_in_page)+1))
    return render(request, 'index.html', {'articles': articles[offset : articles_in_page * page],
    'article_count': article_count, 'pages_range':pages_range})

Django/blog/about/templates/about.html
{% extends 'base.html' %}
<!-- {% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>About</title>
    <link rel="stylesheet" href="{% static 'about_style.css' %}">
</head>
<body>
    <nav class="nav">
        <a class="nav__link_1" href="#">Dog's blog</a>
        <a class="nav__link" href="#">Home</a>
        <a class="nav__link" href="#">Create article</a>
        <a class="nav__link" href="#">About</a>
    </nav> -->
    
{% block content %}
<div class="container">
    <h1 class="h1">Dog's blog!</h1>
    <!-- <img class="img" alt="picture" src="{% static 'img/pitbull.png' %}"> -->
    <p class="p">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In consequat ut risus eu lacinia. Pellentesque venenatis iaculis nibh sit amet pretium. Nam ullamcorper ut ante nec tempus. Fusce varius dignissim velit elementum iaculis. In at neque turpis. Nulla nec placerat justo. Nulla augue nulla, accumsan et velit a, ultricies dignissim ante. Vestibulum fringilla lacus sollicitudin lectus sollicitudin, eget pharetra purus ornare. Pellentesque blandit nisi libero, nec feugiat libero tristique nec. Cras vehicula ligula libero, eget consequat sapien aliquam at. Sed viverra elementum ornare. Phasellus tellus erat, tincidunt sed scelerisque quis, aliquet id arcu.
    In eleifend semper augue quis congue. In hac habitasse platea dictumst. Ut varius nisl et nibh finibus maximus. Fusce malesuada lobortis aliquet. Vivamus mauris orci, luctus eu libero et, imperdiet tempor nunc. Maecenas aliquam dui id ante ornare, ac faucibus ante maximus. Sed vitae venenatis massa. Fusce id ullamcorper eros, eu porttitor erat. Cras pulvinar condimentum odio in eleifend. Nam eget pharetra enim, vel euismod risus.
    Etiam sagittis felis nisi, sit amet fringilla magna luctus ut. Praesent egestas efficitur ipsum, a imperdiet elit tristique non. Vestibulum aliquet interdum eros id rutrum. Donec gravida sem arcu, eu tristique est condimentum efficitur. Donec nec suscipit libero. Nam est lectus</p>
    <p class="p">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec suscipit velit. Cras eu luctus mauris. Nam interdum nisi vitae ex ullamcorper, semper fermentum augue pretium. Nam sed tincidunt metus, ac interdum eros. Duis rutrum purus nec lacus tristique posuere. Fusce scelerisque diam vel mi accumsan, ac scelerisque diam eleifend.</p>
    <h1 class="h1_">Send your message to Dany!</h1>
    <form class="form" method="POST">
        {% csrf_token %}
        <div>
            <label class="label" for="id_email">Email</label>
        </div>
        <div>
            <input class="input" type="text" placeholder="Email" name="email" maxlength="254" required_id="id_email">
        </div> 
        <div>
            <label class="label" for="id_first_name">First name</label>
        </div>
        <div>
            <input class="input" type="text" placeholder="First name" name="first_name" maxlength="100" required_id="id_first_name">
        </div>
        <div>
            <label class="label" for="id_last_name">Last name</label>
        </div>
        <div>
            <input class="input" type="text" placeholder="Last name" name="last_name" maxlength="100" required_id="id_last_name">
        </div> 
        <div>
            <label class="label" for="id_message">Message</label>
        </div>
        <div>
            <input class="input" type="text" placeholder="Message" name="message" maxlength="200" required_id="id_message">
        </div>
        <div>
            <input class="allow_mailing" type="checkbox" placeholder="Allow mailing" name="allow_mailing" id="id_allow_mailing">
            <label class="label" for="id_allow_mailing">Allow mailing</label>
        </div> 
        <div>
            <input class="button" type="submit" value="Send">
        </div>    
    </form>
</div>
    {% endblock %}
    <!-- <hr>
    <h4 class="h4">@All rights reserved 2021-2022</h4>
    {% if data %}
    {% for a in data %}
        <p>{{ a.email}}</p>
        <p>{{ a.first_name}}</p>
        <p>{{ a.last_name}}</p>
        <p>{{ a.message}}</p>
    {% endfor %}    
    {% endif %}
</body>
</html> -->

Django/blog/article/templates/article_create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'article_styles.css' %}">
<div class='container'>
    <h1>Create article</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- {{ form }} -->
        <div class="div">
            <label class="label" for="id_title">Title</label>
        </div>
        <div>
            <input class="form-control" type="text" name="title" maxlength="100" required_id='id_title' placeholder="Enter title">
        </div>
        <div class="div">
            <label class="label" for="id_short_description">Short description</label>
        </div>
        <div>
            <textarea class="form-control" rows="2" name="shot_description" maxlength="300" required_id='id_short_description' placeholder="Enter short description"></textarea>
        </div>
        <div class="div">
            <label class="label" for="id_description">Description</label>
        </div>
        <div>
            <textarea class="form-control" rows="5" name="description" maxlength="2000" required_id='id_description' placeholder="Enter description"></textarea>
        </div>
        <div class="div">
            <label class="label" for="id_image">Upload image</label>
        </div>
        <div>
            <input type="file" class="form-control" name="image" required_id="id_image" >
        </div>
        <div class="center">
            <input class="button" type="submit" value="Send">
        </div>
        {% if error %}
        {% for k,n in error.items %}
        <h2>Error in</h2>
        <h2>{{k}}</h2>
        <h2>{{n}}</h2>
        {% endfor %}
        {% endif %}
    </form>
</div>
{% endblock %}

Django/blog/article/templates/article_show.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'article_show.css' %}">
<div class="list-group">
    <div class="centered-container top-margin-container text-center">
        <h3 class="mb-1">{{article.title}}</h3>
        <h5 class="mb-1">{{article.shot_description}}</h5>
    </div>
    <div class="centered-container top-margin-container text-center">
        {% if article.image.url %}<img class="img-thumbnail" alt="picture"src="{{article.image.url}}"> 
        {% else %}
        Without image
        {% endif %}
    </div>
    <div>
        <h6>{{article.description}}</h6>
        <h6>{{article.created_date}}</h6>
    </div>
    <div class="centered-container top-margin-container text-center">
        <h3 class="mb-1">Comments</h3>
    </div>
    <form method="POST">
        {% csrf_token %}
        <div class="div">
            <label class="label" for="id_name">Enter your name</label>
        </div>
        <div>
            <input class="form-control" type="text" name="name" maxlength="100" required_id='id_name' placeholder="Name">
        </div>
        <div class="div">
            <label class="label" for="id_text">Enter comment</label>
        </div>
        <div>
            <textarea class="form-control" rows="3" name="text" required_id='id_text' placeholder="Text"></textarea>
        </div>
        <div class="center">
            <input class="button" type="submit" value="Send">
        </div>
    </form>
    {% if comments %}
    {% for comment in comments %}
        <div class="d-flex w-100 justify-content-between">
            <h6 class="mb-1">Autor: {{comment.name}}</h6>
            <h6 class="mb-1">{{comment.created_date}}</h6>
        </div>
        <div class="desc">
            <h6 class="h6">Comment: {{comment.text}}</h6>
        </div>
        <hr>
    {% endfor%}
    {% endif %}
</div>
<!-- <form method="POST">
    {{ form }}
    <input type="button">

</form> -->


{% endblock %}

Django/blog/main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>blog</title>
    <link rel="stylesheet" href="{% static 'about_style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <nav class="nav">
        <a class="nav__link_1" href="{% url 'index' %}">Dog's blog</a>
        <a class="nav__link" href="{% url 'index' %}">Home</a>
        <a class="nav__link" href="{% url 'article_create' %}">Create article</a>
        <a class="nav__link" href="{% url 'about_data' %}">About</a>
    </nav>
    {% block content %}
    {% endblock %}
    <hr class="hr">
    <footer class="footer">@All rights reserved 2021-2022</footer>
</body>
</html>

Django/blog/main/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'main.css' %}">
<h1 class="centered-container text-uppercase text-center">welcome to dog's blog</h1>
{% if articles %}
<div class="list-group">
    {% for article in articles %}
    <a href="/article_show/{{article.id}}/" class="list-group-item list-group-item-action flex-column align-items-start article-items-action">
        <div class="d-flex w-100 justify-content-between">
            <h4 class="mb-1">{{article.title}}</h4>
            <h6 class="mb-1">{{article.created_date}}</h6>
        </div>
        <div class="centered-container top-margin-container text-center">
            {% if article.image.url %}<img class="img-thumbnail" alt="picture"src="{{article.image.url}}"> 
            {% else %}
            Without image
            {% endif %}
        </div>
        <div class="desc">
            <h6 class="h6">{{article.shot_description}}</h6>
        </div>
        <div>
            <h4 class="centered-container text-center">Comments: {{article.comments.count}}</h4>
        </div>
    </a>
</div>
    {% endfor %}
{% else %}
No articles
{% endif %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      <li class="page-item">
        <a class="page-link" href="/1" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
    {% for page in pages_range%}
      <li class="page-item"><a class="page-link" href="/{{ page }}">{{ page }}</a></li>
    {% endfor %}
      <li class="page-item">
        <a class="page-link" href="/{{ pages_range|last }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    </ul>
  </nav>

{% endblock%}